version: 0.2
env:
  variables:
    APP_ID: "idb"
phases:
  install:
    commands:
      - echo installing nodejs...
      - curl -sL https://deb.nodesource.com/setup_12.x | bash -
      - apt-get install -y nodejs  #aws code build use ubuntu environement
  pre_build:
    commands:
      - echo installing dependencies...
      - npm i -g @angular/cli
      - npm install
  build:
    commands:
      # - echo testing...
      # - echo building...
      - echo APP_ID is ${APP_ID}
      - echo ${CODEBUILD_SOURCE_VERSION}
      - echo ${CODEBUILD_WEBHOOK_TRIGGER}
      - echo GH_BRANCH is ${BRANCH_NAME}
      - ng build --prod
  post_build:
    commands:
      - mv appspec.yml ./dist/my-dream-app
      - mv scripts ./dist/my-dream-app
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: dist/my-dream-app
